---
on-game-end:
  # teleports the player to the default level. If false is given a teleport-level needs to be supplied,
  # otherwise teleporting will be disabled.
  teleport-default-level: true
  # teleports the player to the given level. This option is only respected if teleport-default-level is false.
  teleport-level: ""
  # the position (X, Y, Z) of the teleport in the level specified above. Supply ~ for all three to use the spawn pos.
  teleport-position:
    - ~
    - ~
    - ~
  # defines the delay in ticks before the players are teleported. (0 or ~ for instant teleport) [default 5s]
  teleport-delay: 100

### NOT IMPLEMENTED ###
time-limit:
  # max-time in ticks (-1 or ~ for infinite)
  max-time: -1
  display:
    # how time should be displayed in chat (only to the players):
    # in what interval to chat the time in ticks (-1 or ~ to disable)
    chat-interval: -1
    # if there should be (additional) chat messages towards the end (75% of time, 10 and 5 sec before)
    chat-towards-end: true
    # display time in popup
    popup: true
...
